import "../public/css/bootstrap.min.css";
import "../public/css/coloring.css";
import "../public/css/plugins.css";
import "../public/css/style.css";
import "slick-carousel/slick/slick-theme.css";
import "slick-carousel/slick/slick.css";
import "./globals.css";

import { Inter } from "next/font/google";
import Preloader from "@/layouts/Preloader";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "NateKodi — DJ Producer",
  description: "Generated by NateKodi",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
      </head>
      <body>
        <Preloader />
        {children}
      </body>
    </html>
  );
}
